name: Deploy Java Project to Azure Function App

on:
  push:
    branches: ["dev"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use windows-latest if necessary, but ubuntu-latest is generally faster for CI

    environment: dev         # References the 'dev' environment in GitHub

    permissions:
      id-token: write        # Required for OIDC authentication
      contents: read

    env:
      AZURE_FUNCTIONAPP_NAME: ctr-dev-cc-app           # Function app name
      AZURE_FUNCTIONAPP_SLOT: ctr-dev-cc-app-test      # Deployment slot name (if using a slot)

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'                        # Java distribution
        java-version: '17'                             # Java version

    - name: Build with Maven and Package as ZIP
      run: mvn clean package azure-functions:package

    - name: Azure Login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Function App Slot
      uses: azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        slot-name: ${{ env.AZURE_FUNCTIONAPP_SLOT }}
        package: 'target/azure-functions/ctr-dev-cc-app/functionapp.zip'  # Path to the generated ZIP file
